## Second Assignment

#### 1) Create a function called **"even_squared"** that receives an integer value **N**, and returns a list containing, in ascending order, the square of each of the even values, from 1 to N, including N if applicable. 

In [1]:
def even_squared():
    N = int(input("Please, enter a number:"))
    values = list(range(1, N+1))
    for i in values:
        if int(i)%2==0:#check if even
            print (i*i)
even_squared()

Please, enter a number:5
4
16


#### 2) Using a while loop and the **input()** function, read an indefinite amount of **integers** until the number read is **-1**. After this process, print two lists on the screen: The first containing the even integers, and the second containing the odd integers. Both must be in ascending order. 

In [6]:
#define the list
number = []
even = []
odd = []

while number!= -1:
    user_input = int(input("Enter an integer : "))
    #add numbers to the list
    number.append(user_input)
    if user_input % 2 == 0:
        even.append(user_input)
    elif user_input % 2 != 0 :
        odd.append(user_input)
    if user_input == -1:
        break
even.sort()
odd.sort()
print("The even integers are",even)
print("The odd integers are",odd)

Enter an integer : 4
Enter an integer : 8
Enter an integer : 77
Enter an integer : -1
The even integers are [4, 8]
The odd integers are [-1, 77]


#### 3) Create a function called **"even_account"** that receives a list of integers, counts the number of existing even elements, and returns this count. 

In [12]:
count= 0
input_string = input("Please, enter elements of a list separated by space ")
even_account = input_string.split()

for i in range(len(even_account)):
    even_account[i] = int(even_account[i])

for numbers in even_account:
    if numbers % 2 == 0:
        count +=1
    
print(" ",count)


Please, enter elements of a list separated by space 7 4 1 2
  2


#### 4) Create a function called **"squared_list"** that receives a list of integers and returns another list whose elements are the squares of the elements of the first. 

In [16]:
input_string = input("Please, enter elements of a list separated by space ")
squared_int = input_string.split()

for i in range(len(squared_int)):
    squared_int[i] = int(squared_int[i])
squared_int = [squared_list ** 2 for squared_list in squared_list]

print(squared_int)

Please, enter elements of a list separated by space 4 2 1
[16, 4, 1]


#### 5) Create a function called **"descending"** that receives two lists of integers and returns a single list, which contains all the elements in descending order, and may include repeated elements. 

In [18]:
input_list1 = input("Please, enter elements of  the first list separated by space ")
list1 = input_list1.split()

for i in range(len(list1)):
    list1[i] = int(list1[i])

input_list2 = input("Please, enter elements of  the second list separated by space ")
list2 = input_list2.split()

for i in range(len(list2)):
    list2[i] = int(list2[i])
    
final_list = [*list1, *list2]
sortedlist = sorted(final_list)
print(sortedlist)

Please, enter elements of  the first list separated by space 4 5 2 1 5
Please, enter elements of  the second list separated by space 7 8 5
[1, 2, 4, 5, 5, 5, 7, 8]


#### 6) Create a function called **"adding"** that receives a list **A**, and an arbitrary number of integers as input. Return a new list containing the elements of **A** plus the integers passed as input, in the order in which they were given. Here is an example: 

>```python
>>>> A = [10,20,30]
>>>> adding(A, 4, 10, 50, 1)
> [10, 20, 30, 4, 10, 50, 1]
```

In [2]:
def adding():
    A = [4, 5, 9]
    input1 = input("Please, enter elements desired separated by space: ")
    randomlist = input1.split()
    
    for i in range(len(randomlist)):
        randomlist[i] = int(randomlist[i])
    
    together_list = A + randomlist
    print(together_list)
adding()

Please, enter elements desired separated by space: 4 8 7
[4, 5, 9, 4, 8, 7]


#### 7) Create a function called **"intersection"** that receives two input lists and returns another list with the values that belong to the two lists simultaneously (intersection) without repetition of values and in ascending order. Use only lists (do not use sets); loops and conditionals. See the example: 

>```python
>>>> A = [-2, 0, 1, 2, 3]
>>>> B = [-1, 2, 3, 6, 8]
>>>> intersection(A,B)
> [2, 3]
```

In [4]:
def intersection ():
    num1 = input("Please, enter elements of  the first list separated by space ")
    listn1 = num1.split()
    
    for i in range(len(listn1)):
        listn1[i] = int(listn1[i])
    
    num2 = input("Please, enter elements of  the second list separated by space ")
    listn2 = num2.split()
    
    for i in range(len(listn2)):
        listn2[i] = int(listn2[i])
    final_list = list(set(listn1).intersection(listn2))
    final_list.sort()
    print (final_list)
intersection ()

Please, enter elements of  the first list separated by space 7 8 4 5 6 9 2
Please, enter elements of  the second list separated by space 2 1 4 5 7 4
[2, 4, 5, 7]


#### 8) Create a function called **"union"** that receives two input lists and returns another list with the union of the elements of the two received, without repetition of elements and in ascending order. Use only lists (do not use sets); loops and conditionals. See the example: 

>```python
>>>> A = [-2, 0, 1, 2]
>>>> B = [-1, 1, 2, 10]
>>>> union(A,B)
> [-2, ,-1, 0, 1, 2, 10]
```

In [17]:
def unionlist ():
    list1 = input("Please, enter elements of  the first list separated by space ")
    listnumber1 = list1.split()
    
    for i in range(len(listnumber1)):
        listnumber1[i] = int(listnumber1[i])
    
    list2 = input("Please, enter elements of  the second list separated by space ")
    listnumber2 = list2.split()
    
    for i in range(len(listnumber2)):
        listnumber2[i] = int(listnumber2[i])
    final_list = list(set().union(listnumber1, listnumber2))
    print(final_list)
unionlist ()

Please, enter elements of  the first list separated by space 47 7 5 8
Please, enter elements of  the second list separated by space 1 4 2 6
[1, 2, 4, 5, 6, 7, 8, 47]


#### 9) Generalize the **"intersection"** function so that it receives an indefinite number of lists and returns the intersection of all of them. Call the new function **intersection2**. 

In [8]:
def intersection2 (*lists):
    return list (set.intersection(*map(set, lists)))
intersection2 ([1,2], [2,4], [2,5])

[2]

## Challenge

#### 10) Create a function named **"matrix"** that implements matrix multiplication:
    
Given the matrices:
    
$A_{m\times n}=
\left[\begin{matrix}
a_{11}&a_{12}&...&a_{1n}\\
a_{21}&a_{22}&...&a_{2n}\\
\vdots &\vdots &&\vdots\\
a_{m1}&a_{m2}&...&a_{mn}\\
\end{matrix}\right]$
    
We will represent then as a list of lists.

$A = [[a_{11},a_{12},...,a_{1n}],[a_{21},a_{22},...,a_{2n}], . . . ,[a_{m1},a_{m2},...,a_{mn}]]$

The **"matrix"** funtion must receive two matrices $A$ e $B$ in the specified format and return $A\times B$

In [15]:
import numpy as np
RA = int(input("Enter the number of rows of matrix A:"))
CA = int(input("Enter the number of columns of matrix A:"))

print("Enter the entries in a single line (separated by space): ")

entriesA = list(map(int, input().split()))
  
A = np.array(entriesA).reshape(RA, CA)
print(A)

Enter the number of rows of matrix A:3
Enter the number of columns of matrix A:3
Enter the entries in a single line (separated by space): 
1 2 5 4 7 8 9 6 4
[[1 2 5]
 [4 7 8]
 [9 6 4]]


In [16]:
RB = int(input("Enter the number of rows of matrix B:"))
CB = int(input("Enter the number of columns of matrix B:"))

print("Enter the entries in a single line (separated by space): ")

entriesB = list(map(int, input().split()))

B = np.array(entriesB).reshape(RB, CB)
print(B)

Enter the number of rows of matrix B:3
Enter the number of columns of matrix B:3
Enter the entries in a single line (separated by space): 
4 2 6 7 5 9 8 4 1
[[4 2 6]
 [7 5 9]
 [8 4 1]]


In [17]:
result = np.dot(A,B)

print(result)

[[ 58  32  29]
 [129  75  95]
 [110  64 112]]
